/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_instil_surge_client_RtspClient */

#ifndef _Included_co_instil_surge_client_RtspClient
#define _Included_co_instil_surge_client_RtspClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_load
  (JNIEnv *, jclass);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    createNativeClientInstance
 * Signature: (Lco/instil/surge/client/RtspClientDelegate;Z)J
 */
JNIEXPORT jlong JNICALL Java_co_instil_surge_client_RtspClient_createNativeClientInstance
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    options
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_options__Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    options
 * Signature: (Ljava/lang/String;Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_options__Ljava_lang_String_2Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    describe
 * Signature: (Ljava/lang/String;Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_describe__Ljava_lang_String_2Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    describe
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_describe__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setup
 * Signature: (Lco/instil/surge/client/SessionDescription;Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setup
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_play__
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    play
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_play__Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_pause__
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    pause
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_pause__Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setTimeRange
 * Signature: (Ljava/util/Date;Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setTimeRange
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setStartTime
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setStartTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setEndTime
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setEndTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    tearDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_tearDown
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    keepAlive
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_keepAlive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_close
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    stopStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_stopStream
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    isInterleavedTransport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_co_instil_surge_client_RtspClient_isInterleavedTransport
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    getPacketBufferDelay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_instil_surge_client_RtspClient_getPacketBufferDelay
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setPacketBufferDelay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setPacketBufferDelay
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
