/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_instil_surge_client_RtspClient */

#ifndef _Included_co_instil_surge_client_RtspClient
#define _Included_co_instil_surge_client_RtspClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_load
  (JNIEnv *, jclass);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    createNativeClientInstance
 * Signature: (Lco/instil/surge/client/RtspClientDelegate;)J
 */
JNIEXPORT jlong JNICALL Java_co_instil_surge_client_RtspClient_createNativeClientInstance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    connect
 * Signature: (Ljava/lang/String;Lco/instil/surge/callbacks/BooleanCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_connect
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setCredentials
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setCredentials
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    describe
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_describe
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setup
 * Signature: (Lco/instil/surge/client/SessionDescription;Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setup
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_play__
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    play
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_play__Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_pause__
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    pause
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_pause__Lco_instil_surge_callbacks_ResponseCallback_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    options
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_options
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    tearDown
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_tearDown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    keepAlive
 * Signature: (Lco/instil/surge/callbacks/ResponseCallback;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_keepAlive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setTimeRange
 * Signature: (Ljava/util/Date;Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setTimeRange
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setStartTime
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setStartTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setEndTime
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setEndTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    isInterleavedTransport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_co_instil_surge_client_RtspClient_isInterleavedTransport
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setInterleavedTransport
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setInterleavedTransport
        (JNIEnv *, jobject, jboolean);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    getPacketBufferDelay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_instil_surge_client_RtspClient_getPacketBufferDelay
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setPacketBufferDelay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setPacketBufferDelay
  (JNIEnv *, jobject, jint);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setTLSCertificateValidationEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setTLSCertificateValidationEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    isTLSCertificateValidationEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_co_instil_surge_client_RtspClient_isTLSCertificateValidationEnabled
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setTLSSelfSignedCertsAllowed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setTLSSelfSignedCertsAllowed
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    tlsSelfSignedCertsAllowed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_co_instil_surge_client_RtspClient_tlsSelfSignedCertsAllowed
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setTLSTrustedCertificate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setTLSTrustedCertificate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    AddAuthenticator
 * Signature: (Lco/instil/surge/authentication/SurgeAuthenticator;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_addAuthenticator
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    RemoveAuthenticator
 * Signature: (Lco/instil/surge/authentication/SurgeAuthenticator;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_removeAuthenticator__Lco_instil_surge_authentication_SurgeAuthenticator_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    RemoveAuthenticator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_removeAuthenticator__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    GetDiagnosticsOnPacketLoss
 * Signature: ()Lco/instil/surge/diagnostics/RtpPacketBufferInfo;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_getDiagnosticsOnPacketLoss
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
