/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_instil_surge_client_RtspClient */

#ifndef _Included_co_instil_surge_client_RtspClient
#define _Included_co_instil_surge_client_RtspClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_load
  (JNIEnv *, jclass);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    createNativeClientInstance
 * Signature: (Lco/instil/surge/client/RtspClientDelegate;)J
 */
JNIEXPORT jlong JNICALL Java_co_instil_surge_client_RtspClient_createNativeClientInstance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    options
 * Signature: ()Lco/instil/surge/client/Response;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_options__
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    options
 * Signature: (Ljava/lang/String;)Lco/instil/surge/client/Response;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_options__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    describe
 * Signature: (Ljava/lang/String;)Lco/instil/surge/client/DescribeResponse;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_describe__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    describe
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lco/instil/surge/client/DescribeResponse;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_describe__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setup
 * Signature: (Lco/instil/surge/client/SessionDescription;)Lco/instil/surge/client/Response;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    play
 * Signature: ()Lco/instil/surge/client/Response;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_play
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    pause
 * Signature: ()Lco/instil/surge/client/Response;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_pause
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setTimeRange
 * Signature: (Ljava/util/Date;Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setTimeRange
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setStartTime
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setStartTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    setEndTime
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_setEndTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    tearDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_tearDown
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    keepAlive
 * Signature: ()Lco/instil/surge/client/Response;
 */
JNIEXPORT jobject JNICALL Java_co_instil_surge_client_RtspClient_keepAlive
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_close
  (JNIEnv *, jobject);

/*
 * Class:     co_instil_surge_client_RtspClient
 * Method:    stopStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_instil_surge_client_RtspClient_stopStream
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
