name: Build App
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Xcode Version to 14
        run: sudo xcode-select -s '/Applications/Xcode_14.0.app/Contents/Developer'
      - name: Build app
        run: |
          cd apple
          cp Harness/Configuration/ApiKeys.xcconfig_sample Harness/Configuration/ApiKeys.xcconfig
          xcodebuild -scheme Harness -project Harness.xcodeproj/ build CODE_SIGNING_ALLOWED=NO
